# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 10.1.1.19
            - name: NFS_PATH
              value: /mnt/truenas-1/Documents
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.1.1.19
            path: /mnt/truenas-1/Documents
